@IsTest
global class ChargeOver_Test_MockHttp implements HttpCalloutMock 
{
	global HTTPResponse respond(HTTPRequest req) 
    {
        System.assertEquals('http://example.com/example/test', req.getEndpoint());
		System.assertEquals('GET', req.getMethod());

        HttpResponse res = new HttpResponse();
		res.setHeader('Content-Type', 'application/json');
		res.setBody('{"example":"test"}');
		res.setStatusCode(200);
		
        return res;
	}
}