/**
 * Deprecated
 */
@isTest
private class TestBatchAssignments {

    static testmethod void testLeadAssignment() {

    //     //run batch class
    //     test.startTest();
    //     BatchProcessLeadAssignment tlead = new BatchProcessLeadAssignment();
    //     Database.executeBatch(tlead);
        
    //     BatchProcessLeadAssignment tla = new BatchProcessLeadAssignment (true);
    //     Database.executeBatch(tla);
    //     test.stopTest();
    }
    
    static testmethod void testAccountAssignment() {
    
    //     //run batch class
    //     test.startTest();
    //     BatchProcessAccountAssignment taccount = new BatchProcessAccountAssignment ();
    //     Database.executeBatch(taccount);
        
    //     BatchProcessAccountAssignment taa = new BatchProcessAccountAssignment (true);
    //     Database.executeBatch(taa);
    //     test.stoptest();
    }
}